### ISSUE TITLE
APK from website crashes but building from source doesn't (Android P)

### ISSUE THREAD

**Issue by PeterMcteague** [OXOIndustries/TiTS-Public#101]
Hi

When I run the latest ARM backer apk from the site, according to adb logcat the following error occurs under Android P DP3 (Android API 28) on my Pixel XL:

```
07-07 18:37:53.003 10599 10599 E intedspace.tit: No implementation found for void com.adobe.air.AIRWindowSurfaceView.nativeSurfaceCreated() (tried Java_com_adobe_air_AIRWindowSurfaceView_nativeSurfaceCreated and Java_com_adobe_air_AIRWindowSurfaceView_nativeSurfaceCreated__)
07-07 18:37:53.005 10599 10599 D AndroidRuntime: Shutting down VM
07-07 18:37:53.007 10599 10599 E AndroidRuntime: FATAL EXCEPTION: main
07-07 18:37:53.007 10599 10599 E AndroidRuntime: Process: air.com.taintedspace.tits, PID: 10599
07-07 18:37:53.007 10599 10599 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for void com.adobe.air.AIRWindowSurfaceView.nativeSurfaceCreated() (tried Java_com_adobe_air_AIRWindowSurfaceView_nativeSurfaceCreated and Java_com_adobe_air_AIRWindowSurfaceView_nativeSurfaceCreated__)
07-07 18:37:53.007 10599 10599 E AndroidRuntime: 	at com.adobe.air.AIRWindowSurfaceView.nativeSurfaceCreated(Native Method)
07-07 18:37:53.007 10599 10599 E AndroidRuntime: 	at com.adobe.air.AIRWindowSurfaceView.surfaceCreated(AIRWindowSurfaceView.java:721)
07-07 18:37:53.007 10599 10599 E AndroidRuntime: 	at android.view.SurfaceView.updateSurface(SurfaceView.java:670)
07-07 18:37:53.007 10599 10599 E AndroidRuntime: 	at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:143)
07-07 18:37:53.007 10599 10599 E AndroidRuntime: 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
07-07 18:37:53.007 10599 10599 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2475)
07-07 18:37:53.007 10599 10599 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
07-07 18:37:53.007 10599 10599 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7184)
07-07 18:37:53.007 10599 10599 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
07-07 18:37:53.007 10599 10599 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
07-07 18:37:53.007 10599 10599 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:696)
07-07 18:37:53.007 10599 10599 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
07-07 18:37:53.007 10599 10599 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-07 18:37:53.007 10599 10599 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-07 18:37:53.007 10599 10599 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
07-07 18:37:53.007 10599 10599 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
07-07 18:37:53.007 10599 10599 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-07 18:37:53.007 10599 10599 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-07 18:37:53.007 10599 10599 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-07 18:37:53.009   915  2081 W ActivityManager:   Force finishing activity air.com.taintedspace.tits/.AppEntry
```

However, when I have built the apk using
* PackageApp.bat
* SWF built using FlashDevelop with overlayed Flex 4.6.0 and AIR 27 SDK's (Which looking at the source appears to be the same config)
* Packager.bat modified to use my systems filepaths
the generated APK runs with no errors.

**Comment by mirh** [comment]
At least since this spring builds, it doesn't seem a problem on my XZ2.
